version: "3"
services:
  app:
    container_name: dev_social
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: dev_social_mongo
    image: mongo
    ports:
      - "27017:27017"
